using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ProductCatalog.Data;
using ProductCatalog.Models;
using ProductCatalog.Services;

namespace ProductCatalog.ViewModels;

[QueryProperty(nameof(ProductId), "ProductId")]
public partial class ProductDetailViewModel : ObservableObject
{
    private readonly DatabaseContext _database;
    private readonly ImageService _imageService;

    private int productId;

    public int ProductId
    {
        get => productId;
        set
        {
            if (SetProperty(ref productId, value))
            {
                if (value > 0)
                {
                    IsEditMode = true;
                    _ = LoadProductAsync(value);
                }
            }
        }
    }

    [ObservableProperty]
    private string name = string.Empty;

    [ObservableProperty]
    private string description = string.Empty;

    [ObservableProperty]
    private string priceText = string.Empty;

    [ObservableProperty]
    private string stockText = string.Empty;

    [ObservableProperty]
    private string category = string.Empty;

    [ObservableProperty]
    private string? imagePath = string.Empty;

    [ObservableProperty]
    private bool isEditMode;

    public List<string> Categories { get; } = new()
    {
        "Electronics",
        "Clothing",
        "Food",
        "Home",
        "Sports",
        "Books",
        "Toys",
        "Other"
    };

    public int ProductId1 { get => productId; set => productId = value; }
    public int ProductId2 { get => productId; set => productId = value; }
    public int ProductId3 { get => productId; set => productId = value; }

    public ProductDetailViewModel(DatabaseContext database, ImageService imageService)
    {
        this._database = database;
        this._imageService = imageService;
    }

    // This partial method is generated by [ObservableProperty] for ProductId
    //public async partial void OnProductIdChanged(int value)
    //{
    //    if (value > 0)
    //    {
    //        IsEditMode = true;
    //        await LoadProductAsync(value); // Sin el _ =
    //    }
    //}

    private async Task LoadProductAsync(int id)
    {
        var product = await _database.GetProductByIdAsync(id);

        if (product != null)
        {
            Name = product.Name;
            Description = product.Description;
            PriceText = product.Price.ToString();
            StockText = product.Stock.ToString();
            ImagePath = product.ImagePath;
            Category = product.Category;
        }
    }

    [RelayCommand]
    private async Task TakePhotoAsync()
    {
        var path = await _imageService.TakePhotoAsync();

        if (path != null)
        {
            // Delete ald image if exist
            if (!string.IsNullOrEmpty(ImagePath))
            {
                _imageService.DeleteImage(ImagePath);
            }

            ImagePath = path;
        }
        else
        {
            await Shell.Current.DisplayAlertAsync("Info", "Could not take photo, Check camera permissions.", "OK");
        }
    }

    [RelayCommand]
    private async Task SelectPhotoAsync()
    {
        var path = await _imageService.SelectPhotoAsync();

        if (path != null)
        {
            // Delete old image if exist
            if (!string.IsNullOrEmpty(ImagePath))
            {
                _imageService.DeleteImage(ImagePath);
            }

            ImagePath = path;
        }
    }

    [RelayCommand]
    private void DeletePhoto()
    {
        if (!string.IsNullOrEmpty(ImagePath))
        {
            _imageService.DeleteImage(ImagePath);
            ImagePath = null;
        }
    }

    [RelayCommand]
    private async Task SaveAsync()
    {
        // Validations
        if (string.IsNullOrWhiteSpace(Name))
        {
            await Shell.Current.DisplayAlertAsync("Error", "Name is required", "OK");
            return;
        }

        if (!decimal.TryParse(PriceText, out decimal price) || price < 0)
        {
            await Shell.Current.DisplayAlertAsync("Error", "Price must be a valid number", "OK");
            return;
        }

        if (!int.TryParse(StockText, out int stock) || stock < 0)
        {
            await Shell.Current.DisplayAlertAsync("Error", "Stock must be a valid number", "OK");
            return;
        }

        if (string.IsNullOrWhiteSpace(Category))
        {
            await Shell.Current.DisplayAlertAsync("Error", "Please select a category", "OK");
            return;
        }

        // Create or update product
        var product = new Product
        {
            Id = ProductId,
            Name = Name,
            Description = Description,
            Price = price,
            Stock = stock,
            ImagePath = ImagePath,
            Category = Category
        };

        await _database.SaveProductAsync(product);
        await Shell.Current.DisplayAlertAsync("Success", "Product saved successfully", "OK");
        await Shell.Current.GoToAsync(".."); // go back
    }

    [RelayCommand]
    private async Task CancelAsync()
    {
        await Shell.Current.GoToAsync("..");
    }
}