using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ProductCatalog.Data;
using ProductCatalog.Models;

namespace ProductCatalog.ViewModels;

[QueryProperty(nameof(ProductId), "ProductId")]
public partial class ProductDetailViewModel : ObservableObject
{
    private readonly DatabaseContext _database;

    [ObservableProperty]
    private int productId;

    [ObservableProperty]
    private string name = string.Empty;

    [ObservableProperty]
    private string description = string.Empty;

    [ObservableProperty]
    private string priceText = string.Empty;

    [ObservableProperty]
    private string stockText = string.Empty;

    [ObservableProperty]
    private string category = string.Empty;

    [ObservableProperty]
    private bool isEditMode;

    public List<string> Categories { get; } = new()
    {
        "Electronics",
        "Clothing",
        "Food",
        "Home",
        "Sports",
        "Books",
        "Toys",
        "Other"
    };

    public ProductDetailViewModel(DatabaseContext database)
    {
        this._database = database;
    }

    // This partial method is generated by [ObservableProperty] for ProductId
    //partial void OnProductIdChanged(int value)
    //{
    //    if (value > 0)
    //    {
    //        IsEditMode = true;
    //        _ = LoadProductAsync(value);
    //    }
    //}

    private async Task LoadProductAsync(int id)
    {
        var product = await _database.GetProductByIdAsync(id);

        if (product != null)
        {
            Name = product.Name;
            Description = product.Description;
            PriceText = product.Price.ToString();
            StockText = product.Stock.ToString();
            Category = product.Category;
        }
    }

    [RelayCommand]
    private async Task SaveAsync()
    {
        // Validations
        if (string.IsNullOrWhiteSpace(Name))
        {
            await Shell.Current.DisplayAlertAsync("Error", "Name is required", "OK");
            return;
        }

        if (!decimal.TryParse(PriceText, out decimal price) || price < 0)
        {
            await Shell.Current.DisplayAlertAsync("Error", "Price must be a valid number", "OK");
            return;
        }

        if (!int.TryParse(StockText, out int stock) || stock < 0)
        {
            await Shell.Current.DisplayAlertAsync("Error", "Stock must be a valid number", "OK");
            return;
        }

        if (string.IsNullOrWhiteSpace(Category))
        {
            await Shell.Current.DisplayAlertAsync("Error", "Please select a category", "OK");
            return;
        }

        // Create or update product
        var product = new Product
        {
            Id = ProductId,
            Name = Name,
            Description = Description,
            Price = price,
            Stock = stock,
            Category = Category
        };

        await _database.SaveProductAsync(product);
        await Shell.Current.DisplayAlertAsync("Success", "Product saved successfully", "OK");
        await Shell.Current.GoToAsync(".."); // go back
    }

    [RelayCommand]
    private async Task CancelAsync()
    {
        await Shell.Current.GoToAsync("..");
    }
}